#+title: CCA picker

Allocating CCAs based on a fixed excel template

* Setup
Ensure that Python 3 is installed, and this folder is downloaded on your local machine.
#+begin_src sh
  cd path/to/repo
  python3 -m venv venv
  . venv/bin/activate
  python3 -m pip install -r requirements.txt
#+end_src

* Usage
1. Place the =.xlsx= file inside the folder.
2. Edit ~IN_FILE~ and ~OUT_FILE~ as desired.
3. Edit ~QUOTA~ to reflect all CCAs
   Make sure that ~None~ is placed where the CCA does not have any quota for that gender.
4. Run the command with
  #+begin_src sh
    # activate the virtual environment
    cd path/to/repo
    . venv/bin/activate
  
    # run script
    python3 __main__.py
  #+end_src

* Algorithm
1. Head count for CCA is filled by picking students at random.
2. If the CCA quota of that student's choice is maxed out, the student is placed on wait list
3. If the student's choice reflects "No Preference", the student is placed on wait list
4. After a full random sweep, the wait list is processed.
5. Students on the wait list who did not have their preference fulfilled because of maxed quota are given their next choice (if it exists, and is not maxed out).
6. Students on the wait list with "No Preference" are allocated the CCA with the lowest headcount
7. Steps 2-6 are performed for all 3 choices.
